# Debug setup, not used in production

services:
  glvd-postgres:
    image: ghcr.io/gardenlinux/glvd-postgres:latest
    hostname: glvd-postgres
    networks:
      - glvd_ingest
    volumes:
      - glvd_db_ingest_volume:/var/lib/postgresql
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glvd -d glvd"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s

  glvd-init:
    image: ghcr.io/gardenlinux/glvd-init:latest
    networks:
      - glvd_ingest
    depends_on:
      glvd-postgres:
        condition: service_healthy
        restart: false
    environment:
      PGHOST: glvd-postgres

  ingest:
    build:
      dockerfile: Containerfile.debug
    networks:
      - glvd_ingest
    depends_on:
      glvd-postgres:
        condition: service_healthy
        restart: false
      glvd-init:
        condition: service_completed_successfully
        restart: false
    environment:
      PGHOST: glvd-postgres
      PGPORT: 5432
      PGDATABASE: glvd
      PGUSER: glvd
      PGPASSWORD: glvd
    command: "sleep infinity"

networks:
  glvd_ingest: {}

volumes:
  glvd_db_ingest_volume:
